#!/bin/bash
#
# this script is invoked from ipscromp_gatekeeper
# until we decide on which ports we want to open, just open all of them...
#
# usage:
#    ipscromp_dynfw [open|close] <IP>


REPO=/var/spool/ipscromp

SSH_PORT='22'


usage()
{
	cat <<EOF
usage: ipscromp_dynfw [open|close] <IP addr>

EOF
}


open_firewall()
{
	#echo "open_firewall for $1"
	EXISTS=$(iptables -C IPSCROMP -s $1 -j ACCEPT 2>&1)
	[ ! -z "$EXISTS" ] && iptables -I IPSCROMP -s $1 -p tcp --dport 22 -j ACCEPT
}


close_firewall()
{
	#echo "close_firewall for $1"
	iptables -D IPSCROMP -s $1 -p tcp --dport 22 -j ACCEPT
}


op=""

while test $# -gt 0; do
	case "$1" in
		open)
			shift
			op=open
			ipaddr="$1"
			;;

		close)
			shift
			op=close
			ipaddr="$1"
			;;
	esac
	shift
done

if [ -z "$op" ]; then
	usage
	exit
fi

if [ -z "$ipaddr" ]; then
	usage
	exit
fi


if [ "$op" = "open" ]; then
	echo "Opening FW for $ipaddr..."
	open_firewall $ipaddr
else
	echo "Closing FW for $ipaddr..."
	close_firewall $ipaddr
fi

